import * as THREE from 'three';
import {archData} from './architecture-data.js';
let seed=9823;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
function batch(scene,g,mat,list,shadow=true){if(!list.length)return;const m=new THREE.InstancedMesh(g,mat,list.length),matrix=new THREE.Matrix4();list.forEach((o,i)=>{matrix.compose(new THREE.Vector3(...o.p),new THREE.Quaternion().setFromEuler(new THREE.Euler(...(o.r||[0,0,0]))),new THREE.Vector3(...o.s));m.setMatrixAt(i,matrix);if(o.c)m.setColorAt(i,new THREE.Color(o.c))});m.castShadow=shadow;m.receiveShadow=true;scene.add(m);return m}
const item=(p,s,r,c)=>({p,s,r,c});
export function makeEnvironment(scene,baseURL){
 seed=9823;const loader=new THREE.TextureLoader(),load=(name,color=false)=>{const t=loader.load(new URL('assets/'+name,baseURL).href);t.wrapS=t.wrapT=THREE.RepeatWrapping;if(color)t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t};
 const stone=new THREE.MeshStandardMaterial({color:'#e6e0ce',roughness:.78,normalMap:load('stone-normal.png'),normalScale:new THREE.Vector2(.22,.22)}),shadowStone=new THREE.MeshStandardMaterial({color:'#b1c3cb',roughness:.85}),metal=new THREE.MeshStandardMaterial({color:'#9c9180',metalness:.72,roughness:.38}),leaf=new THREE.MeshStandardMaterial({color:'#63865a',roughness:1}),glow=new THREE.MeshBasicMaterial({color:'#d1faff'});
 const map=load('stone-color.png',true),normal=load('stone-normal.png'),rough=load('stone-rough.png');for(const t of [map,normal,rough])t.repeat.set(4,4);
 const floor=new THREE.Mesh(new THREE.CircleGeometry(12.18,128),new THREE.MeshStandardMaterial({map,normalMap:normal,roughnessMap:rough,normalScale:new THREE.Vector2(.22,.22),color:'#f4f0e4',roughness:.7,metalness:.08}));floor.rotation.x=-Math.PI/2;floor.position.y=-.018;floor.receiveShadow=true;scene.add(floor);
 for(const r of [3.9,4.05,9.75,9.92,11.75]){const m=new THREE.Mesh(new THREE.TorusGeometry(r,.022,5,128),metal);m.rotation.x=Math.PI/2;m.position.y=-.001;scene.add(m)}
 const blocks=[],columns=[],caps=[],spires=[],arches=[],trims=[],plants=[],islands=[],cores=[];
 const box=new THREE.BoxGeometry(1,1,1),cylinder=new THREE.CylinderGeometry(1,1,1,12),cone=new THREE.ConeGeometry(1,1,10),arch=new THREE.BufferGeometry();arch.setAttribute('position',new THREE.Float32BufferAttribute(archData.positions,3));arch.setIndex(archData.indices);arch.computeVertexNormals();
 // Decoration stays beyond the original arena. Open sightlines around the playable floor.
 for(let i=0;i<48;i++){const a=i*Math.PI/24;blocks.push(item([Math.sin(a)*12.6,-.12,Math.cos(a)*12.6],[1.64,.42,1.2],[0,a,0]));if(i%4===0){const x=Math.sin(a)*13.3,z=Math.cos(a)*13.3;columns.push(item([x,.6,z],[.34,1.2,.34]));caps.push(item([x,1.23,z],[.64,.16,.64]));}}
 function tower(x,z,h,r=1.4){columns.push(item([x,h*.45,z],[r,h*.9,r]));caps.push(item([x,.3,z],[r*2.9,.6,r*2.9]));for(let k=1;k<5;k++){caps.push(item([x,h*k/5,z],[r*2.4,.18,r*2.4]));for(const s of [-1,1])trims.push(item([x+s*r*.85,h*k/5+.65,z+r*.99],[.08,1.3,.1]));}spires.push(item([x,h+2,z],[r*1.15,5,r*1.15]));cores.push(item([x,h+4.6,z],[.10,.45,.10]));for(const dx of [-1,1])for(const dz of [-1,1]){columns.push(item([x+dx*r,h*.56,z+dz*r],[.18,h*1.1,.18]));spires.push(item([x+dx*r,h*1.13,z+dz*r],[.30,1.9,.30]));}}
 // Layered cathedral: arcades, flying buttresses, pinnacles and high central spire.
 for(const side of [-1,1]){for(let i=0;i<6;i++){const z=-23+i*7,x=side*23;columns.push(item([x,3.7,z],[.5,7.4,.5]));arches.push(item([x,5.2,z+3.5],[3.5,2.4,1],[0,Math.PI/2,0]));caps.push(item([x,10.1,z+3.5],[1.8,.35,7.5]));spires.push(item([x,11.6,z],[.48,3,.48]));}tower(side*9,-23,13,1.15);tower(side*17,-36,22,1.45);}
 for(let i=-2;i<=2;i++){const x=i*7;arches.push(item([x,5,-35],[3.4,3.1,1.7]));columns.push(item([x-3.5,2.5,-35],[.62,5,.62]));caps.push(item([x,10.9,-35],[7.1,.4,1.6]));}
 tower(0,-47,33,2.6);tower(-8,-44,24,1.35);tower(8,-44,25,1.35);
 for(const side of [-1,1])for(let i=0;i<3;i++)arches.push(item([side*(6+i*4),10+i*3,-42],[4,3.2,1],[0,0,side*-.28]));
 // Giant broken orbital ruin and bridge silhouettes, spatial geometry rather than a backdrop poster.
 for(const [x,y,z,r,tilt] of [[-27,19,-55,17,.23],[24,25,-66,22,-.3]]){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.55,8,90,Math.PI*1.65),shadowStone);ring.position.set(x,y,z);ring.rotation.set(0,tilt,tilt);scene.add(ring);for(let i=0;i<15;i++){const a=i/15*Math.PI*1.65;caps.push(item([x+Math.cos(a)*r,y+Math.sin(a)*r,z],[1.5,.6,1.9],[0,0,a]));}}
 for(let i=0;i<9;i++){const x=25+i*5,y=14+Math.sin(i*.3)*2;blocks.push(item([x,y,-55],[5.2,.7,2.4]));columns.push(item([x,y-2,-55],[.3,4,.3]));}
 // Floating limestone islands with grass terraces and trailing vegetation.
 for(let i=0;i<16;i++){const a=i/16*Math.PI*2,r=43+rand()*33,x=Math.sin(a)*r,z=Math.cos(a)*r,y=8+rand()*16,s=2+rand()*4;islands.push(item([x,y-s*.7,z],[s,s*1.8,s],[0,0,Math.PI]));caps.push(item([x,y+.15,z],[s*1.55,.32,s*1.3]));for(let j=0;j<6;j++)plants.push(item([x+(rand()-.5)*s*1.5,y+.38,z+(rand()-.5)*s*1.3],[.4+rand(),.2+rand()*.3,.5+rand()],null,'#749065'));if(i%3===0)tower(x,z,8,.65);for(let j=0;j<3;j++)plants.push(item([x+s*.5,y-1-j*.6,z],[.23,.75,.3],null,'#60846d'));}
 for(let i=0;i<160;i++){const a=rand()*Math.PI*2,r=13.1+rand()*3,x=Math.sin(a)*r,z=Math.cos(a)*r;plants.push(item([x,.1+rand()*.23,z],[.18+rand()*.6,.15+rand()*.4,.2+rand()*.5],null,i%7===0?'#e4d6a4':'#738a56'));}
 batch(scene,box,stone,blocks);batch(scene,cylinder,stone,columns);batch(scene,box,stone,caps);batch(scene,cone,stone,spires);batch(scene,arch,stone,arches);batch(scene,box,metal,trims);batch(scene,new THREE.IcosahedronGeometry(1,0),leaf,plants);batch(scene,cone,shadowStone,islands,false);batch(scene,box,glow,cores,false);
 const sky=new THREE.Mesh(new THREE.SphereGeometry(118,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,vertexShader:'varying vec3 d;void main(){d=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec3 d;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);}void main(){vec3 v=normalize(d);float h=smoothstep(-.05,.85,v.y);vec3 c=mix(vec3(.83,.9,.95),vec3(.23,.48,.78),h);vec2 p=v.xz/(max(.15,v.y+.3))*2.;float n=noise(p*3.)*.55+noise(p*6.)*.28+noise(p*12.)*.17;float clouds=smoothstep(.49,.72,n)*smoothstep(-.05,.2,v.y);c=mix(c,vec3(.99,.98,.96),clouds*.88);float sun=pow(max(0.,dot(v,normalize(vec3(-.4,.7,.4)))),100.);c+=sun*.22;gl_FragColor=vec4(c,1.);}`}));scene.add(sky);
 const flags=[];for(const side of [-1,1]){const flag=new THREE.Mesh(new THREE.PlaneGeometry(1.35,3.8,5,12),new THREE.MeshStandardMaterial({color:side<0?'#3b577d':'#7189a4',roughness:.9,side:THREE.DoubleSide}));flag.position.set(side*9,9,-22);flag.userData.base=Float32Array.from(flag.geometry.attributes.position.array);scene.add(flag);flags.push(flag);}
 return {update(clock){flags.forEach((f,k)=>{const p=f.geometry.attributes.position,b=f.userData.base;for(let i=0;i<p.count;i++)p.setZ(i,Math.sin(clock*1.4+b[i*3+1]*1.4+k)*.15*(1.9-b[i*3+1])/3.8);p.needsUpdate=true;f.geometry.computeVertexNormals()})}};
}
