import * as THREE from 'three';
const V=p=>new THREE.Vector3(p.x,p.y,p.z),Y=new THREE.Vector3(0,1,0);
// Adult proportion rig, in unscaled game units. Its topology is independent of the PBD doll.
export const REST={pelvis:[0,1.38,0],spine:[0,1.64,0],chest:[0,1.94,0],neck:[0,2.09,0],head:[0,2.29,0],
 shoulderL:[-.275,1.96,0],elbowL:[-.455,1.48,.07],handL:[-.7,1,.2],shoulderR:[.275,1.96,0],elbowR:[.455,1.48,.07],handR:[.7,1,.2],
 hipL:[-.18,1.36,0],kneeL:[-.23,.75,.06],footL:[-.28,.16,.22],hipR:[.18,1.36,0],kneeR:[.23,.75,.06],footR:[.28,.16,.22]};
export const PARENT={pelvis:null,spine:'pelvis',chest:'spine',neck:'chest',head:'neck',shoulderL:'chest',elbowL:'shoulderL',handL:'elbowL',shoulderR:'chest',elbowR:'shoulderR',handR:'elbowR',hipL:'pelvis',kneeL:'hipL',footL:'kneeL',hipR:'pelvis',kneeR:'hipR',footR:'kneeR'};
const TARGET={pelvis:'spine',spine:'chest',chest:'neck',neck:'head',shoulderL:'elbowL',elbowL:'handL',shoulderR:'elbowR',elbowR:'handR',hipL:'kneeL',kneeL:'footL',hipR:'kneeR',kneeR:'footR'};
export function axes(direction,face=0){const y=direction.clone().normalize();if(y.lengthSq()<.1)y.copy(Y);const f=new THREE.Vector3(Math.sin(face),0,Math.cos(face)),x=new THREE.Vector3().crossVectors(y,f);if(x.lengthSq()<1e-6)x.set(Math.cos(face),0,-Math.sin(face));x.normalize();const z=new THREE.Vector3().crossVectors(x,y).normalize();return new THREE.Quaternion().setFromRotationMatrix(new THREE.Matrix4().makeBasis(x,y,z))}
// Analytic two-link IK keeps wrists/ankles attached to existing gameplay endpoints.
export function solveJoint(start,end,pole,a,b){const delta=end.clone().sub(start),distance=delta.length();if(distance<1e-6)return start.clone().addScaledVector(pole.clone().normalize(),a);const dir=delta.divideScalar(distance),stretch=Math.max(1,distance/(a+b-.001)),la=a*stretch,lb=b*stretch,x=(distance*distance+la*la-lb*lb)/(2*distance),h=Math.sqrt(Math.max(0,la*la-x*x));let bend=pole.clone().sub(start).addScaledVector(dir,-pole.clone().sub(start).dot(dir));if(bend.lengthSq()<1e-8){bend=new THREE.Vector3(0,0,1).addScaledVector(dir,-dir.z);if(bend.lengthSq()<1e-8)bend.set(1,0,0)}return start.clone().addScaledVector(dir,x).addScaledVector(bend.normalize(),h)}
export class HeroineRig{
 constructor(root){this.bones={};this.world={};this.names=Object.keys(REST);for(const name of this.names){const b=new THREE.Bone();b.name=name;b.matrixAutoUpdate=false;this.bones[name]=b;(PARENT[name]?this.bones[PARENT[name]]:root).add(b)}this.setWorld(Object.fromEntries(this.names.map(n=>[n,new THREE.Vector3(...REST[n])])),0);root.updateMatrixWorld(true);this.skeleton=new THREE.Skeleton(this.names.map(n=>this.bones[n]));this.skeleton.calculateInverses();}
 setWorld(points,face,widthScale=1){const matrices={};for(const n of this.names){const target=TARGET[n],direction=target?points[target].clone().sub(points[n]):points.neck.clone().sub(points.chest),restLength=target?new THREE.Vector3(...REST[target]).distanceTo(new THREE.Vector3(...REST[n])):1,scale=target?direction.length()/restLength:1;const world=new THREE.Matrix4().compose(points[n],axes(direction,face),new THREE.Vector3(widthScale,scale,widthScale));matrices[n]=world;this.bones[n].matrix.copy(PARENT[n]?matrices[PARENT[n]].clone().invert().multiply(world):world);this.bones[n].matrixWorldNeedsUpdate=true;}this.world=points;}
 update(d){const s=d.spec.scale,source=d.nodes,up=V(source[1].p).sub(V(source[0].p)).normalize(),right=new THREE.Vector3(Math.cos(d.face),0,-Math.sin(d.face)),forward=new THREE.Vector3(Math.sin(d.face),0,Math.cos(d.face));if(up.lengthSq()<.1)up.copy(Y);
  const pelvis=V(source[0].p).addScaledVector(up,.33*s),points={pelvis,spine:pelvis.clone().addScaledVector(up,.24*s),chest:pelvis.clone().addScaledVector(up,.52*s),neck:pelvis.clone().addScaledVector(up,.66*s),head:pelvis.clone().addScaledVector(up,.85*s)};
  // Retain head-hit and collapse direction, while compressing the old overlong neck.
  const liveHead=V(source[2].p).sub(V(source[1].p)).normalize();points.head.addScaledVector(liveHead.clone().sub(up),.16*s);
  for(const [suffix,side]of [['L',-1],['R',1]]){const find=name=>source.find(n=>n.name===name&&Math.sign(n.rest.x)===side);const hand=find(side<0?'offhand':'hand'),elbow=find('elbow'),knee=find('knee'),foot=find('foot');points['shoulder'+suffix]=points.chest.clone().addScaledVector(right,side*.275*s).addScaledVector(up,.015*s);points['hand'+suffix]=V(hand.p);points['elbow'+suffix]=solveJoint(points['shoulder'+suffix],points['hand'+suffix],V(elbow.p).addScaledVector(right,side*.095*s),.51*s,.51*s);points['hip'+suffix]=pelvis.clone().addScaledVector(right,side*.17*s).addScaledVector(up,.005*s);points['foot'+suffix]=V(foot.p);points['knee'+suffix]=solveJoint(points['hip'+suffix],points['foot'+suffix],V(knee.p).addScaledVector(forward,.2*s),.62*s,.62*s);}
  this.setWorld(points,d.face,s);this.scale=s;return points;
 }
 nodeName(n){if(n.name==='hip')return'pelvis';if(['chest','head'].includes(n.name))return n.name;const suffix=n.rest.x<0?'L':'R';return ({shoulder:'shoulder',elbow:'elbow',hand:'hand',offhand:'hand',knee:'knee',foot:'foot'}[n.name]||'hand')+suffix}
 segment(d,l){let a=this.world[this.nodeName(d.nodes[l.a])],b=this.world[this.nodeName(d.nodes[l.b])];if(d.nodes[l.a].name==='hip'&&d.nodes[l.b].name==='knee')a=this.world['hip'+(d.nodes[l.b].rest.x<0?'L':'R')];if(d.nodes[l.b].name==='head')b=this.world.neck;return[a,b]}
 dispose(){this.skeleton.dispose()}
}
