"""Bake a pointed Gothic arch as indexed mesh data (Python, reproducible offline)."""
import math,json
from pathlib import Path
positions=[];indices=[]
# Two quadratic sweeps meet at a pointed crown; front/back profiles form a solid stone rib.
path=[]
for side in [-1,1]:
 for j in range(25):
  t=j/24 if side<0 else 1-j/24
  x=side*(1-t)**2;y=2*t*(1-t)*1.5+t*t*1.7
  path.append((x,y))
for i,(x,y) in enumerate(path):
 a=path[max(0,i-1)];b=path[min(len(path)-1,i+1)];dx=b[0]-a[0];dy=b[1]-a[1];n=math.hypot(dx,dy) or 1
 for offset,z in [(-.09,-.14),(.09,-.14),(.09,.14),(-.09,.14)]:positions.extend([round(x-dy/n*offset,6),round(y+dx/n*offset,6),z])
for i in range(len(path)-1):
 for k in range(4):
  a=i*4+k;b=i*4+(k+1)%4;c=b+4;d=a+4;indices.extend([a,b,d,b,c,d])
indices.extend([0,2,1,0,3,2]);n=(len(path)-1)*4;indices.extend([n,n+1,n+2,n,n+2,n+3])
out=Path(__file__).resolve().parents[1]/'visual-src/architecture-data.js'
out.write_text('// Generated by tools/make-architecture.py\nexport const archData='+json.dumps({'positions':positions,'indices':indices},separators=(',',':'))+';\n')
print('Baked pointed arch:',len(positions)//3,'vertices')
