"""Bake a continuous flared wrap skirt, with shallow pleats and a straight rear hem.
Python mesh authoring replaces the former paired, thick rear plates.
"""
import math,json
from pathlib import Path
p=[];idx=[];colors=[];segments=64;rows=14
# Hip-node local units. One connected rear sheet; opening exists only at the front.
for i in range(rows+1):
 t=i/rows
 for j in range(segments+1):
  a=math.pi/2+.52+j/segments*(math.tau-1.04)
  pleat=math.cos(a*12)*.035*t*t
  rx=1.12+.49*t;rz=.78+.23*t
  x=math.cos(a)*(rx+pleat);z=math.sin(a)*(rz+pleat)
  y=.14-t*1.88
  p.extend([round(x,6),round(y,6),round(z,6)])
  # Broad charcoal hem and subtle woven seams read as clothing from the gameplay camera.
  border=i>=rows-1 or j in [0,segments]
  seam=j%8==0 and 0<i<rows-1
  colors.extend([.018,.023,.036] if border else [.40,.43,.46] if seam else [.77,.765,.73])
for i in range(rows):
 for j in range(segments):
  a=i*(segments+1)+j;b=a+1;c=a+segments+1;d=c+1
  idx.extend([a,b,c,b,d,c])
out=Path(__file__).resolve().parents[1]/'visual-src/couture-data.js'
out.write_text('// Generated by tools/make-couture.py\nexport const skirtData='+json.dumps({'positions':p,'indices':idx,'colors':colors},separators=(',',':'))+';\n')
print('Baked continuous skirt:',len(p)//3,'vertices,',len(idx)//3,'triangles')
