"""Generate a weighted, continuous costume mesh for the independent heroine skeleton.
Python/NumPy mesh authoring; rerun to edit silhouette without a DCC installation.
"""
from pathlib import Path
import json,math,numpy as np
names=['pelvis','spine','chest','neck','head','shoulderL','elbowL','handL','shoulderR','elbowR','handR','hipL','kneeL','footL','hipR','kneeR','footR']
p=[];indices=[];weights=[];bones=[];colors=[]
def srgb(v):
 v=v/255;return v/12.92 if v<=.04045 else ((v+.055)/1.055)**2.4
def color(rgb):return [round(srgb(v),5) for v in rgb]
white=color([224,223,217]);black=color([25,29,40]);seam=color([112,124,139])
def add_rings(rings,sides):
 offset=len(p)//3
 for center,right,forward,rx,rz,bi,bw,col in rings:
  for j in range(sides):
   a=j/sides*math.tau;q=center+right*(math.cos(a)*rx)+forward*(math.sin(a)*rz)
   p.extend(round(float(v),5) for v in q);bones.extend(bi+[0]*(4-len(bi)));weights.extend(bw+[0]*(4-len(bw)));colors.extend(col(a))
 for i in range(len(rings)-1):
  for j in range(sides):
   a=offset+i*sides+j;b=offset+i*sides+(j+1)%sides;c=b+sides;d=a+sides;indices.extend([a,b,d,b,c,d])
 # End caps prevent visible hollow tubes at extreme poses.
 for first,reverse in [(offset,True),(offset+(len(rings)-1)*sides,False)]:
  for j in range(1,sides-1):indices.extend([first,first+j+(0 if reverse else 1),first+j+(1 if reverse else 0)])
rings=[]
for i in range(29):
 t=i/28;y=1.30+t*.69
 rx=np.interp(y,[1.30,1.4,1.57,1.73,1.86,1.99],[.245,.245,.183,.21,.26,.225]);rz=np.interp(y,[1.30,1.48,1.67,1.85,1.99],[.145,.123,.135,.158,.12])
 k=0 if y<1.64 else 1;a,b=(1.38,1.64) if k==0 else (1.64,1.94);w=max(0,min(1,(y-a)/(b-a)))
 def col(angle,y=y):
  side=abs(math.cos(angle));return black if side>.77 or (math.sin(angle)<0 and abs(math.cos(angle))<.1) or y<1.42 else white
 rings.append((np.array([0,y,0]),np.array([1,0,0]),np.array([0,0,1]),rx,rz,[k,k+1],[round(1-w,5),round(w,5)],col))
add_rings(rings,40)
for side,suffix in [(-1,'L'),(1,'R')]:
 for kind in ['arm','leg']:
  if kind=='arm':points=[np.array([side*.32,1.96,0]),np.array([side*.48,1.48,.07]),np.array([side*.7,1,.2])];boneNames=['shoulder'+suffix,'elbow'+suffix];radii=[.09,.08,.063,.075,.047]
  else:points=[np.array([side*.18,1.36,0]),np.array([side*.23,.75,.06]),np.array([side*.28,.16,.22])];boneNames=['hip'+suffix,'knee'+suffix];radii=[.12,.127,.067,.09,.055]
  rings=[]
  for i in range(33):
   t=i/32;k=0 if t<=.5 else 1;u=t*2-k;center=points[k]*(1-u)+points[k+1]*u;tangent=points[k+1]-points[k];tangent/=np.linalg.norm(tangent);right=np.cross(tangent,[0,0,1]);right/=np.linalg.norm(right);forward=np.cross(right,tangent);radius=float(np.interp(t,[0,.24,.5,.73,1],radii));w=max(0,min(1,(t-.43)/.14))
   rings.append((center,right,forward,radius,radius*.86,[names.index(n) for n in boneNames],[round(1-w,5),round(w,5)],lambda angle:black))
  add_rings(rings,28)
data={'positions':p,'indices':indices,'skinIndices':bones,'skinWeights':weights,'colors':colors}
out=Path(__file__).resolve().parents[1]/'visual-src/heroine-mesh-data.js';out.write_text('// Generated by tools/make-heroine-mesh.py\nexport const bodyData='+json.dumps(data,separators=(',',':'))+';\n')
print('Baked costume:',len(p)//3,'vertices,',len(indices)//3,'triangles')
