"""Bake a stylized adult head with jaw, cheek, orbital, nasal and cranial volumes."""
from pathlib import Path
import math,json
from scipy.interpolate import PchipInterpolator
width=PchipInterpolator([-.9,-.82,-.68,-.45,-.18,.15,.45,.70,.88,.98],[.035,.21,.36,.49,.61,.63,.62,.49,.29,.025])
depth=PchipInterpolator([-.9,-.7,-.4,0,.3,.6,.85,.98],[.04,.30,.46,.58,.61,.52,.31,.025])
p=[];idx=[];uv=[];cols=64;rows=48
for i in range(rows+1):
 y=.98-i/rows*1.88;rx=float(width(y));rz=float(depth(y))
 for j in range(cols+1):
  a=j/cols*math.tau;x=math.cos(a)*rx;z=math.sin(a)*rz
  if z>0:
   f=max(0,math.sin(a))**7
   nose=.095*math.exp(-(x/.068)**2-((y+.03)/.30)**2)+.068*math.exp(-(x/.083)**2-((y+.19)/.085)**2)
   eyes=.066*math.exp(-((abs(x)-.275)/.14)**2-((y-.12)/.12)**2)
   cheek=.033*math.exp(-((abs(x)-.36)/.18)**2-((y+.14)/.16)**2)
   chin=.022*math.exp(-(x/.22)**2-((y+.67)/.13)**2)
   z+=f*(nose-eyes+cheek+chin)
  p.extend([round(x,6),round(y,6),round(z+.03,6)]);uv.extend([j/cols,i/rows])
for i in range(rows):
 for j in range(cols):
  a=i*(cols+1)+j;b=a+1;c=a+cols+1;d=c+1;idx.extend([a,b,c,b,d,c])
out=Path(__file__).resolve().parents[1]/'visual-src/head-data.js';out.write_text('// Generated by tools/sculpt-heroine-head.py\nexport const headData='+json.dumps({'positions':p,'indices':idx,'uvs':uv},separators=(',',':'))+';\n');print('Baked head:',len(p)//3,'vertices')
